### ISSUE TITLE
Bar Graph tooltip is not showing

### ISSUE THREAD

**Issue by nishantvarshnay** [cox-auto-kc/react-d3-responsive#37]

**Comment by drew-thorson** [comment]
this should be fixed with version 0.1.9 of react-d3-responsive.  It was part of pull request #35

**Comment by nishantvarshnay** [comment]
Thanks..it is working

**Comment by nishantvarshnay** [comment]
Thanks Drew..it is working..

One more thing there is no redraw/update bar chart even provided data has
been updated..I have already put a issue in repo #36 ..could you check and
provide the solution.

Regards,
-Nishant Varshney


On 27-Mar-2017 11:12 PM, "Drew Thorson" <notifications@github.com> wrote:

this should be fixed with version 0.1.9 of react-d3-responsive. It was part
of pull request #35
<https://github.com/cox-auto-kc/react-d3-responsive/pull/35>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cox-auto-kc/react-d3-responsive/issues/37#issuecomment-289515651>,
or mute the thread

**Comment by drew-thorson** [comment]
Thanks Nishant. I will look into this.
