### ISSUE TITLE
Trendline in charts

### ISSUE THREAD

**Issue by LalithKumarN** [cox-auto-kc/react-d3-responsive#7]
Would like to have a trendline option especially in Scatterplot chart as shown in the attachment.
![trendline](https://cloud.githubusercontent.com/assets/20685640/17224616/4fe51976-54c7-11e6-941d-e6154e02a7b3.PNG)

**Comment by drew-thorson** [comment]
Resolved in 0990cefba3de2de973fd8708092a68ac958b8684
